spring:
  datasource:
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lwt-test?characterEncoding=utf8&useSSL=true
    schema:
      - classpath:sql/tbl_saleman_info.sql
